const CLINICS_DATA_2 = [
{id:"barrientos",name:"Clínica Dental Barrientos Menéndez",address:"Calle Asturias, 1, bajo, 33004 Oviedo",ref:"en pleno centro de Oviedo",city:"Oviedo",valuePoints:"instalaciones modernas, especializada en implantología con carga inmediata y ortodoncia invisible, 4.9 estrellas en más de 50 reseñas",promo:"Implantes: arcada superior de seis implantes por 12.500 euros o desde 260 euros al mes. Ortodoncia: ortodoncia invisible desde 150 euros al mes",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes","ortodoncia"],econQualif:true},
{id:"chroma",name:"Chroma Odontología Avanzada",address:"Calle Príncipe de la Paz, 1, 06001 Badajoz",ref:"justo al lado de Cash Converters",city:"Badajoz",valuePoints:"6 años de trayectoria, cirujano con más de 20 años, cirujana maxilofacial para pacientes sin hueso, laboratorio propio",promo:"un 20% de descuento en implantes más un 10% en la corona, con cuotas desde 21 euros al mes para implante unitario y 85 euros al mes para cuatro implantes",qualifDoc:"DNI",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos. Portugueses: no cualificamos (no podrán financiar) pero agendamos",financing:"3 a 24 meses sin intereses. Hasta 60 meses con intereses",treatments:["implantes"],econQualif:true},
{id:"flordent",name:"Clínica Flordent",address:"Calle Pere Jacas, 19, 08800 Vilanova i la Geltrú, Barcelona",ref:"en Vilanova i la Geltrú",city:"Vilanova i la Geltrú",valuePoints:"4 años de trayectoria, implantólogo con más de 10 años, sistema de análisis de imagen de última generación, sedación completa y carga inmediata, implantes de titanio y coronas de zirconio",promo:"cuotas desde 25 euros al mes para el implante unitario y desde 130 euros al mes para seis implantes",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina, Terceros, Autónomos",financing:"Entre 12 y 24 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"caobadent",name:"Caobadent Clínica Dental",address:"Calle Zaragoza, 1, 28934 Móstoles, Madrid",ref:"en Móstoles",city:"Móstoles",valuePoints:"doctores con más de 20 años de experiencia, cursos y técnicas nuevas, excelentes reseñas, escáner y TAC",promo:"Ortodoncia: ortodoncia convencional por 899 euros, autoligada por 1.899 euros o desde 79 euros al mes, y ortodoncia invisible por 2.699 euros. Carillas: paquete especial de seis carillas por 999 euros",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos (No ASNEF)",financing:"Hasta 24 meses sin intereses",treatments:["ortodoncia","carillas"],econQualif:true,econQualifAll:true},
{id:"colvi",name:"Colvi",address:"Avenida Capitán Ontañón, Edificio Plaza Mayor y Edificio María Cristina, Algeciras",ref:"en Avenida Capitán Ontañón",city:"Algeciras",valuePoints:"Dental: implantólogo con más de 15 años, laboratorio local. Estética: única clínica en Campo de Gibraltar con certificación FHOS",promo:"sobredentadura sobre cuatro implantes desde 55 euros al mes, o prótesis fija sobre seis implantes desde 91 euros al mes",qualifDoc:"DNI o NIE",qualifEcon:"Implantes: Nómina, Jubilados, Terceros, Autónomos | Estética: No se cualifica",financing:"3 a 60 meses sin intereses, cuota mínima 20€",treatments:["implantes","estetica_fhos"],econQualif:true,scriptOverrides:{estetica_fhos:"estetica_fhos"}},
{id:"smiledent-leon",name:"Clínica Dental Smiledent León",address:"Calle Burgo Nuevo, 36, Bajo, 24001 León",ref:"en León",city:"León",valuePoints:"cirujanos odontólogos, excelentes reseñas en Google, tecnología de escáner, carga inmediata previa valoración",promo:"un 20% de descuento en tu tratamiento de implantes",qualifDoc:"DNI",qualifEcon:"Nómina (+1000€), Jubilados (pensión contributiva), Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"smiledent-gijon",name:"Clínica Dental Smiledent Gijón",address:"Calle Granados, 1, 33204 Gijón",ref:"en Gijón",city:"Gijón",valuePoints:"implantólogo con más de 6 años de experiencia, excelentes reseñas en Google, tecnología de escáner, prótesis provisionales",promo:"un 20% de descuento, con cuotas desde 80 euros al mes para implante con corona en 48 meses, y 110 euros al mes para arcada completa",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina (+2000€)",financing:"Hasta 48 meses",treatments:["implantes"],econQualif:true},
{id:"nunez",name:"Clínica Dental Núñez-Cobos",address:"Calle de Goya, 109, local, 28009 Madrid",ref:"en pleno Barrio de Salamanca",city:"Madrid",valuePoints:"5 años abierta, cirujana con más de 12 años en implantes, Certificado Excelencia Profesional 2024, galardón Mejores Médicos 2025, TAC incluido",promo:"Implantes: 10% de descuento en implantes. Blanqueamiento: antes 550 euros, ahora rebajado a 400 euros",qualifDoc:"Implantes: DNI o NIE | Blanqueamiento: DNI, NIE o Pasaporte",qualifEcon:"Solo documentación (no se cualifica económicamente)",financing:"Detalles en clínica",treatments:["implantes","blanqueamiento"],econQualif:false},
{id:"paretsdent",name:"Clínica Dental Paretsdent",address:"Avenida Cataluña, 77, Bajos, Parets del Vallès, Barcelona",ref:"en Parets del Vallès",city:"Parets del Vallès",valuePoints:"más de 10 años abierta, implantóloga con más de 15 años, excelentes reseñas en Google",promo:"Implantes: 20% de descuento, con implante y corona desde 50 euros al mes en 36 meses. Ortodoncia: brackets desde 90 euros al mes o Invisalign desde 120 euros al mes, con blanqueamiento de regalo",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Con intereses",treatments:["implantes","ortodoncia"],econQualif:false,scriptOverrides:{implantes:"simplificado",ortodoncia:"simplificado"}},
{id:"espai",name:"Espai Zen Dental",address:"Calle Guitarrista Fortea, 11, 12005 Castellón de la Plana",ref:"en Castellón de la Plana",city:"Castellón",valuePoints:"cirujana con años de experiencia y 3 años en carga inmediata, clínica familiar, implantes de alta gama",promo:"un 30% de descuento solo esta semana, pasando el implante unitario de 1.400 a 980 euros, con financiación hasta en 60 meses",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Hasta 60 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"fonseca",name:"Dental Fonseca y Obando",address:"Calle del General Ricardos, 138, 28019 Madrid",ref:"en General Ricardos",city:"Madrid",valuePoints:"8 años abierta, TAC y panorámica incluidos, clínica familiar, implantóloga con más de 15 años, ortodoncista con 20 años",promo:"prótesis provisional gratuita con tu tratamiento",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina",financing:"Sin intereses hasta 24 meses. Con intereses hasta 60 meses",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"implantes_fonseca"}},
{id:"marinabaixa",name:"Odonto·Estética Marina Baixa",address:"Carrer la Carretera, 34, Bajo, 03530 La Nucia, Alicante",ref:"en La Nucía",city:"La Nucia",valuePoints:"abierta desde 2022, implantólogo con más de 20 años, clínica familiar sin rotación de doctores, TAC en clínica",promo:"un 20% de descuento y facilidades de financiación hasta en 60 meses",qualifDoc:"No se cualifica",qualifEcon:"No se cualifica",financing:"Hasta 60 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"smailo",name:"Smailo",address:"Calle Libreros, 46, 28805 Alcalá de Henares",ref:"en la Calle Libreros de Alcalá de Henares",city:"Alcalá de Henares",valuePoints:"equipo multidisciplinar y tecnología diagnóstica avanzada",promo:"un estudio y valoración diagnóstica integral totalmente gratuitos y sin compromiso",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"nuno_perez",name:"Nuño + Pérez Odontólogos",address:"Paseo de la Reina Cristina, 1, 28014 Madrid",ref:"a pocos pasos de la estación de Atocha",city:"Madrid",valuePoints:"especialistas con amplia experiencia y tecnología odontológica de vanguardia",promo:"",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Financiación disponible con DNI, NIE o pasaporte + nómina, jubilación, terceros o autónomos",treatments:["implantes"],econQualif:true}
,{id:"implantclinic",name:"Implant Clinic",address:"Plaza de los Pontos, 6, 03203 Elche, Alicante",ref:"en Elche",city:"Elche",valuePoints:"especialistas en implantología avanzada y rehabilitación oral",promo:"un diagnóstico y estudio completo valorado en 350 euros, totalmente gratis",qualifDoc:"DNI / NIE comunitario",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Financiación disponible con DNI / NIE comunitario + nómina, jubilados, terceros o autónomos",treatments:["implantes"],econQualif:true}
,{id:"ardenne",name:"Ardenne Dental",address:"Avenida España, 61, 43882 Segur de Calafell, Tarragona",ref:"en Segur de Calafell",city:"Segur de Calafell",valuePoints:"especialistas en tratamientos integrales de implantología",promo:"precios promocionales especiales en implantes según valoración clínica",qualifDoc:"No aplica",qualifEcon:"No hay financiación. Se confirma capacidad real de pago particular",financing:"No hay financiación",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"ardenne_implantes"}}
,{id:"odos",name:"Odos Dental",address:"Calle de Gaztambide, 31, 28015 Madrid",ref:"en el barrio de Chamberí",city:"Madrid",valuePoints:"especialistas en implantología avanzada y tratamiento multidisciplinar del sueño",promo:"",qualifDoc:"DNI, NIE o pasaporte",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible: DNI / NIE / pasaporte + Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",treatments:["implantes","apnea"],econQualif:true,scriptOverrides:{implantes:"simplificado",apnea:"apnea_odos"}}
,{id:"castelldent",name:"Castelldent",address:"Avenida Primer de Maig, 12, bajos 3, 08860 Castelldefels, Barcelona",ref:"en Castelldefels",city:"Castelldefels",valuePoints:"equipo de implantólogos altamente cualificados",promo:"",qualifDoc:"DNI / NIE",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"videsdental",name:"Vides Dental",address:"Avenida Ribera Alta, 5, 46292 Alcántara del Júcar, Valencia",ref:"en Alcántara del Júcar",city:"Alcantara del Xuquer",valuePoints:"especialistas en implantología y prótesis avanzada",promo:"un 20% de descuento en prótesis fija sobre cuatro implantes, o prótesis semifija sobre cuatro implantes por 3.990 euros, válida hasta final de mes",qualifDoc:"DNI / NIE",qualifEcon:"Nómina ( + 1 año), pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"caredentjerez",name:"Clínica Dental Caredent Jerez",address:"Avenida de Méjico, 11, 11405 Jerez de la Frontera, Cádiz",ref:"en Jerez de la Frontera",city:"Jerez de la Frontera",valuePoints:"especialistas en implantología y cirugía oral",promo:"implante con corona desde 21 euros al mes en 60 meses, o arcada completa desde 97 euros al mes",qualifDoc:"Cualquier documento válido",qualifEcon:"Se acepta todo menos ASNEF",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"zendental",name:"Zen Dental",address:"Calle Castillo de Atienza, 1 bis, 28232 Las Rozas de Madrid, Madrid",ref:"con aparcamiento gratuito para pacientes",city:"Las Rozas de Madrid",valuePoints:"Realizan carga inmediata. Estacionamiento en parking gratuito.",promo:"un 30% de descuento y opciones de financiación sin intereses",qualifDoc:"DNI / NIE / pasaporte",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"marinadental",name:"Marina Dental",address:"Avenida Puerto de Santa María, 1, 03710 Calpe, Alicante",ref:"en Calpe",city:"Calp",valuePoints:"especialistas en implantología dental con tecnología avanzada",promo:"un 20% de descuento en tu tratamiento de implantes",qualifDoc:"DNI / NIE / pasaporte",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"soniadent",name:"Clínica Dental SoniaDent",address:"Plaza de la Independencia, 6, 1º 1ª, 08242 Manresa, Barcelona",ref:"en la Plaza de la Independencia de Manresa",city:"Manresa",valuePoints:"atención odontológica personalizada y especialistas en implantes",promo:"",qualifDoc:"DNI",qualifEcon:"Nómina + de 1200€ / Pensión contributiva + de 1200€ / Terceros + de 1200€ / Autónomos / No ASNEF",financing:"En 3, 6 y 12 meses sin intereses.",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
];
CLINICS_DATA.push(...CLINICS_DATA_2);

