const CLINICS_DATA_2 = [
{id:"barrientos",name:"Clínica Dental Barrientos Menéndez",address:"C. Asturias, 1, bajo, 33004 Oviedo",ref:"",city:"Oviedo",valuePoints:"instalaciones modernas, especializada en implantología con carga inmediata y ortodoncia invisible, 4.9 estrellas en más de 50 reseñas",promo:"Implantes: Arcada superior 6 implantes 12.500€, desde 260€/mes. Ortodoncia: OI desde 150€/mes",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes","ortodoncia"],econQualif:true},
{id:"chroma",name:"Chroma Odontología Avanzada",address:"Príncipe de la Paz, 1, 06001 Badajoz",ref:"al lado del Cash Converters",city:"Badajoz",valuePoints:"6 años de trayectoria, cirujano con más de 20 años, cirujana maxilofacial para pacientes sin hueso, laboratorio propio",promo:"20% en implantes + 10% en corona. 21€/mes unitario. 85€/mes 4 implantes",qualifDoc:"DNI",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos. Portugueses: no cualificamos (no podrán financiar) pero agendamos",financing:"3 a 24 meses sin intereses. Hasta 60 meses con intereses",treatments:["implantes"],econQualif:true},
{id:"flordent",name:"Clínica Flordent",address:"Calle Pere Jacas, 19, 08800 Vilanova i la Geltrú, Barcelona",ref:"",city:"Vilanova i la Geltrú",valuePoints:"4 años de trayectoria, implantólogo con más de 10 años, sistema de análisis de imagen de última generación, sedación completa y carga inmediata, implantes de titanio y coronas de zirconio",promo:"25€/mes unitario. 130€/mes 6 implantes. Estética: 15% dto",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina, Terceros, Autónomos",financing:"Entre 12 y 24 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"caobadent",name:"Caobadent Clínica Dental",address:"C. Zaragoza, 1, 28934 Móstoles, Madrid",ref:"",city:"Móstoles",valuePoints:"doctores con más de 20 años de experiencia, cursos y técnicas nuevas, excelentes reseñas, escáner y TAC",promo:"Ortodoncia Autoligada: 1899€, 79€/mes. Invisible: 2699€. Convencional: 899€. Carillas: 6 carillas por 999€",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos (No ASNEF)",financing:"Hasta 24 meses sin intereses",treatments:["ortodoncia","carillas"],econQualif:true,econQualifAll:true},
{id:"colvi",name:"Colvi",address:"Av. Capitán Ontañón, Ed. Plaza Mayor, Algeciras / Ed. Mª Cristina, Algeciras",ref:"",city:"Algeciras",valuePoints:"Dental: implantólogo con más de 15 años, laboratorio local. Estética: única clínica en Campo de Gibraltar con certificación FHOS",promo:"Dental: Sobredentadura 4 implantes desde 55€/mes. Fija 6 implantes desde 91€/mes",qualifDoc:"DNI o NIE",qualifEcon:"Implantes: Nómina, Jubilados, Terceros, Autónomos | Estética: No se cualifica",financing:"3 a 60 meses sin intereses, cuota mínima 20€",treatments:["implantes","estetica_fhos"],econQualif:true,scriptOverrides:{estetica_fhos:"estetica_fhos"}},
{id:"smiledent-leon",name:"Clínica Dental Smiledent León",address:"Calle Burgo Nuevo, 36, Bajo, 24001 León",ref:"",city:"León",valuePoints:"cirujanos odontólogos, excelentes reseñas en Google, tecnología de escáner, carga inmediata previa valoración",promo:"20% dto",qualifDoc:"DNI",qualifEcon:"Nómina (+1000€), Jubilados (pensión contributiva), Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"smiledent-gijon",name:"Clínica Dental Smiledent Gijón",address:"C. Granados, 1, 33204 Gijón",ref:"",city:"Gijón",valuePoints:"implantólogo con más de 6 años de experiencia, excelentes reseñas en Google, tecnología de escáner, prótesis provisionales",promo:"20% dto. 80€/mes implante+corona (48 meses). 110€/mes arcada completa",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina (+2000€)",financing:"Hasta 48 meses",treatments:["implantes"],econQualif:true},
{id:"nunez",name:"Clínica Dental Núñez-Cobos",address:"Calle de Goya, 109, local, Salamanca, 28009 Madrid",ref:"Barrio Salamanca",city:"Madrid",valuePoints:"5 años abierta, cirujana con más de 12 años en implantes, Certificado Excelencia Profesional 2024, galardón Mejores Médicos 2025, TAC incluido",promo:"Implantes: 10% dto. Blanqueamiento: Antes 550€, ahora 400€",qualifDoc:"Implantes: DNI o NIE | Blanqueamiento: DNI, NIE o Pasaporte",qualifEcon:"Solo documentación (no se cualifica económicamente)",financing:"Detalles en clínica",treatments:["implantes","blanqueamiento"],econQualif:false},
{id:"paretsdent",name:"Clínica Dental Paretsdent",address:"Avda. Catalunya 77, Bajos, Parets del Vallès, Barcelona",ref:"",city:"Parets del Vallès",valuePoints:"más de 10 años abierta, implantóloga con más de 15 años, excelentes reseñas en Google",promo:"20% dto. Implante+Corona: 50€/mes (36 meses). Ortodoncia: Brackets desde 90€/mes. Invisalign desde 120€/mes. Blanqueamiento de regalo",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Con intereses",treatments:["implantes","ortodoncia"],econQualif:false,scriptOverrides:{implantes:"simplificado",ortodoncia:"simplificado"}},
{id:"espai",name:"Espai Zen Dental",address:"c/ Guitarrista Fortea 11, 12005 Castellón de la Plana",ref:"",city:"Castellón",valuePoints:"cirujana con años de experiencia y 3 años en carga inmediata, clínica familiar, implantes de alta gama",promo:"30% dto (solo esta semana). IU: 1400€ → 980€. Financiación hasta 60 meses",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Hasta 60 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"fonseca",name:"Dental Fonseca y Obando",address:"Calle del Gral. Ricardos, 138, 28019 Madrid",ref:"",city:"Madrid",valuePoints:"8 años abierta, TAC y panorámica incluidos, clínica familiar, implantóloga con más de 15 años, ortodoncista con 20 años",promo:"Prótesis provisional gratuita con tu tratamiento",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina",financing:"Sin intereses hasta 24 meses. Con intereses hasta 60 meses",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"implantes_fonseca"}},
{id:"marinabaixa",name:"Odonto·Estética Marina Baixa",address:"Carrer la Carretera, 34, Bajo, 03530 La Nucia, Alicante",ref:"",city:"La Nucia",valuePoints:"abierta desde 2022, implantólogo con más de 20 años, clínica familiar sin rotación de doctores, TAC en clínica",promo:"20% dto. Financiación hasta 60 meses",qualifDoc:"No se cualifica",qualifEcon:"No se cualifica",financing:"Hasta 60 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"smailo",name:"Smailo",address:"Calle Libreros 46, 28805 Alcalá de Henares",ref:"",city:"Alcalá de Henares",valuePoints:"",promo:"Valoración gratuita",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"nuno_perez",name:"Nuño + Pérez Odontólogos",address:"Paseo de la Reina Cristina, 1, Atocha, 28014 Madrid",ref:"Atocha",city:"Madrid",valuePoints:"",promo:"",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Financiación disponible con DNI, NIE o pasaporte + nómina, jubilación, terceros o autónomos",treatments:["implantes"],econQualif:true}
,{id:"implantclinic",name:"Implant Clinic",address:"Plaça dels Pontós, 6, 03203 Elche, Alicante",ref:"",city:"Elche",valuePoints:"",promo:"Diagnóstico valorado en 350 euros, totalmente gratis",qualifDoc:"DNI / NIE comunitario",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Financiación disponible con DNI / NIE comunitario + nómina, jubilados, terceros o autónomos",treatments:["implantes"],econQualif:true}
,{id:"ardenne",name:"Ardenne Dental",address:"Av. Espanya, 61, 43882 Segur de Calafell, Tarragona",ref:"",city:"Segur de Calafell",valuePoints:"",promo:"Precios promocionales en implantes según el caso clínico",qualifDoc:"No aplica",qualifEcon:"No hay financiación. Se confirma capacidad real de pago particular",financing:"No hay financiación",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"ardenne_implantes"}}
,{id:"odos",name:"Odos Dental",address:"C. de Gaztambide, 31, 28015 Madrid",ref:"",city:"Madrid",valuePoints:"",promo:"",qualifDoc:"DNI, NIE o pasaporte",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible: DNI / NIE / pasaporte + Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",treatments:["implantes","apnea"],econQualif:true,scriptOverrides:{implantes:"simplificado",apnea:"apnea_odos"}}
,{id:"castelldent",name:"Castelldent",address:"Av. Primer de Maig, 12, bajos 3, 08860 Castelldefels, Barcelona",ref:"",city:"Castelldefels",valuePoints:"",promo:"",qualifDoc:"DNI / NIE",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"videsdental",name:"Vides Dental",address:"Avenida Ribera Alta 5, Alcantara del Xuquer, 46292, Valencia",ref:"",city:"Alcantara del Xuquer",valuePoints:"",promo:"Prótesis fija sobre 4 implantes: 20% de descuento. Prótesis semifija sobre 4 implantes: 3990€. Promoción disponible hasta final de mes.",qualifDoc:"DNI / NIE",qualifEcon:"Nómina ( + 1 año), pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"caredentjerez",name:"Clínica Dental Caredent Jerez",address:"Av. de Méjico, 11, 11405 Jerez de la Frontera, Cádiz",ref:"",city:"Jerez de la Frontera",valuePoints:"",promo:"Implante + corona: 21,47€/mes en 60 meses. Arcada completa: 97,58€/mes.",qualifDoc:"Cualquier documento válido",qualifEcon:"Se acepta todo menos ASNEF",financing:"Financiación disponible",treatments:["implantes","ortodoncia"],econQualif:true,scriptOverrides:{implantes:"estricto",ortodoncia:"estricto"}}
,{id:"zendental",name:"Zen Dental",address:"C. Castillo de Atienza, 1 bis, 28232 Las Rozas de Madrid, Madrid",ref:"",city:"Las Rozas de Madrid",valuePoints:"Realizan carga inmediata. Estacionamiento en parking gratuito.",promo:"30% de descuento. Financiación sin intereses.",qualifDoc:"DNI / NIE / pasaporte",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"marinadental",name:"Marina Dental",address:"Avinguda Puerto de Santa María, 1, 03710 Calp, Alicante",ref:"",city:"Calp",valuePoints:"",promo:"20% de descuento",qualifDoc:"DNI / NIE / pasaporte",qualifEcon:"Nómina, Pensión contributiva (Jubilados), Terceros, Autónomos",financing:"Financiación disponible",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}
,{id:"soniadent",name:"Clínica Dental SoniaDent",address:"Plaza de la Independència, 6, 1º1º, 08242 Manresa, Barcelona",ref:"",city:"Manresa",valuePoints:"",promo:"",qualifDoc:"DNI",qualifEcon:"Nómina + de 1200€ / Pensión contributiva + de 1200€ / Terceros + de 1200€ / Autónomos / No ASNEF",financing:"En 3, 6 y 12 meses sin intereses.",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"estricto"}}

];
CLINICS_DATA.push(...CLINICS_DATA_2);
