const CLINICS_DATA_2 = [
{id:"barrientos",name:"Clínica Dental Barrientos Menéndez",address:"C. Asturias, 1, bajo, 33004 Oviedo",ref:"",city:"Oviedo",valuePoints:"instalaciones modernas, especializada en implantología con carga inmediata y ortodoncia invisible, 4.9 estrellas en más de 50 reseñas",promo:"Implantes: Arcada superior 6 implantes 12.500€, desde 260€/mes. Ortodoncia: OI desde 150€/mes",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes","ortodoncia"],econQualif:true},
{id:"chroma",name:"Chroma Odontología Avanzada",address:"Príncipe de la Paz, 1, 06001 Badajoz",ref:"al lado del Cash Converters",city:"Badajoz",valuePoints:"6 años de trayectoria, cirujano con más de 20 años, cirujana maxilofacial para pacientes sin hueso, laboratorio propio",promo:"20% en implantes + 10% en corona. 21€/mes unitario. 85€/mes 4 implantes",qualifDoc:"DNI",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos. Portugueses: no cualificamos (no podrán financiar) pero agendamos",financing:"3 a 24 meses sin intereses. Hasta 60 meses con intereses",treatments:["implantes"],econQualif:true},
{id:"flordent",name:"Clínica Flordent",address:"Calle Pere Jacas, 19, 08800 Vilanova i la Geltrú, Barcelona",ref:"",city:"Vilanova i la Geltrú",valuePoints:"4 años de trayectoria, implantólogo con más de 10 años, sistema de análisis de imagen de última generación, sedación completa y carga inmediata, implantes de titanio y coronas de zirconio",promo:"25€/mes unitario. 130€/mes 6 implantes. Estética: 15% dto",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina, Terceros, Autónomos",financing:"Entre 12 y 24 meses",treatments:["implantes"],econQualif:true},
{id:"santrafael",name:"Centro Médico Dental Sant Rafael",address:"Calle de Sant Llorenç, 79, 08202 Sabadell, Barcelona",ref:"",city:"Sabadell",valuePoints:"38 años abierta, una de las más prestigiosas de Sabadell, 99% valoraciones 5 estrellas en Google y Doctoralia, carga inmediata y escáner",promo:"Implantes: 10% dto. Desde 1140€. Ortodoncia: 20% dto + blanqueamiento de regalo",qualifDoc:"DNI o NIE",qualifEcon:"Implantes: Nómina, Jubilados, Terceros, Autónomos | Ortodoncia: Solo documentación",financing:"Hasta 48 meses sin intereses",treatments:["implantes","ortodoncia"],econQualif:true},
{id:"smiling",name:"Centro Dental Smiling",address:"C/ de Hortaleza, 70, Centro, 28004 Madrid",ref:"parking de farmacia cerca",city:"Madrid",valuePoints:"abierta desde 2005, odontóloga con más de 30 años de experiencia, excelentes reseñas en Google, escáner 3D",promo:"Valoración gratuita. Si acceden al tratamiento de carillas, blanqueamiento de regalo (valorado en 800€)",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Hasta 24 meses sin intereses a partir de 1000€",treatments:["carillas"],econQualif:true,econQualifAll:true},
{id:"caobadent",name:"Caobadent Clínica Dental",address:"C. Zaragoza, 1, 28934 Móstoles, Madrid",ref:"",city:"Móstoles",valuePoints:"doctores con más de 20 años de experiencia, cursos y técnicas nuevas, excelentes reseñas, escáner y TAC",promo:"Ortodoncia Autoligada: 1899€, 79€/mes. Invisible: 2699€. Convencional: 899€. Carillas: 6 carillas por 999€",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos (No ASNEF)",financing:"Hasta 24 meses sin intereses",treatments:["ortodoncia","carillas"],econQualif:true,econQualifAll:true},
{id:"colvi",name:"Colvi",address:"Av. Capitán Ontañón, Ed. Plaza Mayor, Algeciras / Ed. Mª Cristina, Algeciras",ref:"",city:"Algeciras",valuePoints:"Dental: implantólogo con más de 15 años, laboratorio local. Estética: única clínica en Campo de Gibraltar con certificación FHOS",promo:"Dental: Sobredentadura 4 implantes desde 55€/mes. Fija 6 implantes desde 91€/mes",qualifDoc:"DNI o NIE",qualifEcon:"Implantes: Nómina, Jubilados, Terceros, Autónomos | Estética: No se cualifica",financing:"3 a 60 meses sin intereses, cuota mínima 20€",treatments:["implantes","estetica_fhos"],econQualif:true,scriptOverrides:{estetica_fhos:"estetica_fhos"}},
{id:"smiledent-leon",name:"Clínica Dental Smiledent León",address:"Calle Burgo Nuevo, 36, Bajo, 24001 León",ref:"",city:"León",valuePoints:"cirujanos odontólogos, excelentes reseñas en Google, tecnología de escáner, carga inmediata previa valoración",promo:"20% dto",qualifDoc:"DNI",qualifEcon:"Nómina (+1000€), Jubilados (pensión contributiva), Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"smiledent-gijon",name:"Clínica Dental Smiledent Gijón",address:"C. Granados, 1, 33204 Gijón",ref:"",city:"Gijón",valuePoints:"implantólogo con más de 6 años de experiencia, excelentes reseñas en Google, tecnología de escáner, prótesis provisionales",promo:"20% dto. 80€/mes implante+corona (48 meses). 110€/mes arcada completa",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina (+2000€)",financing:"Hasta 48 meses",treatments:["implantes"],econQualif:true},
{id:"nunez",name:"Clínica Dental Núñez-Cobos",address:"Calle de Goya, 109, local, Salamanca, 28009 Madrid",ref:"Barrio Salamanca",city:"Madrid",valuePoints:"5 años abierta, cirujana con más de 12 años en implantes, Certificado Excelencia Profesional 2024, galardón Mejores Médicos 2025, TAC incluido",promo:"Implantes: 10% dto. Blanqueamiento: Antes 550€, ahora 400€",qualifDoc:"Implantes: DNI o NIE | Blanqueamiento: DNI, NIE o Pasaporte",qualifEcon:"Solo documentación (no se cualifica económicamente)",financing:"Detalles en clínica",treatments:["implantes","blanqueamiento"],econQualif:false},
{id:"soler",name:"Clínica Dental & Estética Soler",address:"Plaza Española, 17, 08903 L'Hospitalet de Llobregat, Barcelona",ref:"",city:"L'Hospitalet",valuePoints:"10 años abierta, implantólogo con más de 8 años, especialista en prótesis con más de 15 años, clínica familiar y cercana",promo:"Implantes: Boca completa 7590€, 180€/mes. Ortodoncia: Brackets 2500€, 117€/mes. Estética: Armonización 499€ (50% dto)",qualifDoc:"DNI",qualifEcon:"Implantes/Ortodoncia: Nómina, Jubilados, Terceros, Autónomos | Estética: No se cualifica",financing:"Detalles en clínica",treatments:["implantes","ortodoncia","estetica_soler"],econQualif:true,econQualifAll:true,scriptOverrides:{estetica_soler:"estetica_soler"}},
{id:"paretsdent",name:"Clínica Dental Paretsdent",address:"Avda. Catalunya 77, Bajos, Parets del Vallès, Barcelona",ref:"",city:"Parets del Vallès",valuePoints:"más de 10 años abierta, implantóloga con más de 15 años, excelentes reseñas en Google",promo:"20% dto. Implante+Corona: 50€/mes (36 meses). Ortodoncia: Brackets desde 90€/mes. Invisalign desde 120€/mes. Blanqueamiento de regalo",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Con intereses",treatments:["implantes","ortodoncia"],econQualif:true},
{id:"espai",name:"Espai Zen Dental",address:"c/ Guitarrista Fortea 11, 12005 Castellón de la Plana",ref:"",city:"Castellón",valuePoints:"cirujana con años de experiencia y 3 años en carga inmediata, clínica familiar, implantes de alta gama",promo:"30% dto (solo esta semana). IU: 1400€ → 980€. Financiación hasta 60 meses",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Hasta 60 meses",treatments:["implantes"],econQualif:false},
{id:"fonseca",name:"Dental Fonseca y Obando",address:"Calle del Gral. Ricardos, 138, 28019 Madrid",ref:"",city:"Madrid",valuePoints:"8 años abierta, TAC y panorámica incluidos, clínica familiar, implantóloga con más de 15 años, ortodoncista con 20 años",promo:"Prótesis provisional gratuita con tu tratamiento",qualifDoc:"DNI o NIE",qualifEcon:"DNI: Nómina, Jubilados, Terceros, Autónomos | NIE: Nómina",financing:"Sin intereses hasta 24 meses. Con intereses hasta 60 meses",treatments:["implantes"],econQualif:true,scriptOverrides:{implantes:"implantes_fonseca"}},
{id:"marinabaixa",name:"Odonto·Estética Marina Baixa",address:"Carrer la Carretera, 34, Bajo, 03530 La Nucia, Alicante",ref:"",city:"La Nucia",valuePoints:"abierta desde 2022, implantólogo con más de 20 años, clínica familiar sin rotación de doctores, TAC en clínica",promo:"20% dto. Financiación hasta 60 meses",qualifDoc:"No se cualifica",qualifEcon:"No se cualifica",financing:"Hasta 60 meses",treatments:["implantes"],econQualif:false,scriptOverrides:{implantes:"simplificado"}},
{id:"stardental",name:"Star Dental",address:"Avenida Nuevo Mundo, 7, Boadilla del Monte, 28660 Madrid",ref:"",city:"Boadilla del Monte",valuePoints:"",promo:"Prótesis sobre implantes: Desde 164€/mes. Implante Unitario + corona: Desde 29€/mes",qualifDoc:"DNI",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"mpelite",name:"MP Elite Dental (Clínica Gaias Valdemoro)",address:"Av. del Mar Mediterráneo, 3, C.C. El Restón, consulta 7, 28342 Valdemoro, Madrid",ref:"Centro Comercial El Restón",city:"Valdemoro",valuePoints:"",promo:"20% dto",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"smailo",name:"Smailo",address:"Calle Libreros 46, 28805 Alcalá de Henares",ref:"",city:"Alcalá de Henares",valuePoints:"",promo:"Valoración gratuita",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"carey",name:"Carey Clínica Dental",address:"C. de Latina, 41, Latina, 28047 Madrid",ref:"",city:"Madrid",valuePoints:"",promo:"IU + Aditamento + Corona: 990€. Arcada Completa: 8500€",qualifDoc:"DNI o NIE",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos (nómina +1500€ para boca completa o arcada)",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true},
{id:"identalitas",name:"iDentalita's O'Donnell",address:"Calle de O'Donnell, 3, Barrio de Salamanca, Madrid",ref:"Barrio de Salamanca",city:"Madrid",valuePoints:"",promo:"20% dto. Implante+corona: 890€. Prótesis fija: desde 175€/mes. Blanqueamiento de regalo para familiar",qualifDoc:"DNI, NIE o Pasaporte",qualifEcon:"Solo documentación (no se cualifica económicamente)",financing:"Detalles en clínica",treatments:["implantes"],econQualif:false},
{id:"rcclinica",name:"RC Clínica Dental",address:"C/ de l'Historiador Diago, 15, Bajo dcha, 46007 Valencia",ref:"",city:"Valencia",valuePoints:"dirigida por el Dr. Rafael Castelló Bugeda, especializado en implantología, estética dental, cirugía bucal y periodoncia",promo:"25% dto. Unitario: desde 26,32€/mes. Boca completa: Antes 14.666€, ahora 10.999€",qualifDoc:"DNI",qualifEcon:"Nómina, Jubilados, Terceros, Autónomos",financing:"Detalles en clínica",treatments:["implantes"],econQualif:true}
];
CLINICS_DATA.push(...CLINICS_DATA_2);
